# Generated by Django 4.2.7 on 2023-12-16 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('car_brand', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_price', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('quantity', models.IntegerField(default=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car/media/uploads/')),
                ('car_brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car_brand.carbrand')),
            ],
        ),
    ]
