# Generated by Django 4.2.7 on 2023-12-18 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_cart_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
