# Generated by Django 4.2.7 on 2023-12-18 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
