# Generated by Django 4.2.7 on 2023-12-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
