# Generated by Django 4.2.7 on 2023-12-20 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='car_brand',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='car_description',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='car_image',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='car_name',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='car_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='car.carmodel'),
        ),
    ]
