# Generated by Django 4.2.7 on 2023-12-21 08:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('car', '0011_remove_cart_car_brand_remove_cart_car_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='car',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='car',
            field=models.ManyToManyField(blank=True, null=True, to='car.carmodel'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
